name: Build 🏗️ Package ️📦
description: Builds a local Nix package

inputs:
  package:
    description: 'Package name to build'
    required: true

runs:
  using: "composite"
  steps:
  - uses: DeterminateSystems/nix-installer-action@v16
    with:
      determinate: true
  - uses: DeterminateSystems/flakehub-cache-action@v1
  - name: Building 👷 ${{ inputs.package }} 📦
    shell: bash
    run: |
      # Try to get license info
      if ! nix eval ".#${{ inputs.package }}.meta.license.spdxId" --raw 2>/dev/null; then
        echo "⚠️ No license found, enabling unfree packages"
        export NIXPKGS_ALLOW_UNFREE=1
        nix build .#${{ inputs.package }} -L --impure
      else
        echo "✅ License found, building normally"
        nix build .#${{ inputs.package }} -L
      fi
