function sysfetch
  fastfetch \
    --logo-padding-right 2 --key-width 6 \
    --percent-type 2 --size-ndigits 0 \
    --separator "" --bar-char-elapsed "" --bar-char-total " " \
    --localip-compact true --display-compact-type original \
    --title-color-user magenta --title-color-host cyan \
    --os-key-color green --host-key-color green --kernel-key-color green --uptime-key-color green --packages-key-color green --shell-key-color green \
    --os-key       "╭─" \
    --host-key     "├─󰟀" \
    --kernel-key   "├─" \
    --uptime-key   "├─󰔚" \
    --packages-key "├─" \
    --shell-key    "╰─" \
    --display-key-color yellow --de-key-color yellow --wm-key-color yellow --theme-key-color yellow --icons-key-color yellow --font-key-color yellow --cursor-key-color yellow --terminal-key-color yellow \
    --display-key  "╭─󰹑" \
    --de-key       "├─󰧨" \
    --wm-key       "├─󱂬" \
    --theme-key    "├─" \
    --icons-key    "├─󰋩" \
    --font-key     "├─" \
    --cursor-key   "├─󰳽" \
    --terminal-key "╰─" \
    --cpu-key-color blue --gpu-key-color blue --memory-key-color blue --swap-key-color blue --disk-key-color blue --localip-key-color blue --locale-key-color blue \
    --cpu-key      "╭─" \
    --gpu-key      "├─󰢮" \
    --memory-key   "├─" \
    --swap-key     "├─󰿡" \
    --disk-key     "├─󰋊" \
    --localip-key  "├─󱦂" \
    --locale-key   "╰─"
end
