theme:
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
