name: "catppuccin-mocha"

palette:
  background: "#1e1e2e" # Base
  text: "#cdd6f4" # Text
  action: "#f5e0dc" # Rosewater
  accent: "#bac2de" # Subtext1
  alert: "#f9e2af" # Yellow
  error: "#f38ba8" # Red
  info: "#89b4fa" # Blue
  success: "#a6e3a1" # Green
