[common]
name = "gws-calendar-insert"
description = "Google Calendar: Create a new event."
metadata = { "version" = "0.22.5", "openclaw" = { "category" = "productivity", "requires" = { "bins" = ["gws"] }, "cliHelp" = "gws calendar +insert --help" }, "upstream" = "https://github.com/googleworkspace/cli", "revision" = "a3768d0e82ad83cca2da97724e46bea4ff0e6dbd" }
license = "Apache-2.0"
