[general]
background = "#1e1e2e"  # Base
border = "#313244"      # Surface0
horizontal_rule = "#45475a"  # Surface1
unread_indicator = "#89b4fa"  # Blue

[text]
primary = "#cdd6f4"     # Text
secondary = "#bac2de"   # Subtext1
tertiary = "#a6adc8"    # Subtext0
success = "#a6e3a1"     # Green
error = "#f38ba8"       # Red

[buttons.primary]
background = "#313244"          # Surface0
background_hover = "#45475a"    # Surface1
background_selected = "#585b70"  # Surface2
background_selected_hover = "#6c7086"  # Overlay0

[buttons.secondary]
background = "#45475a"          # Surface1
background_hover = "#585b70"    # Surface2
background_selected = "#6c7086"  # Overlay0
background_selected_hover = "#7f849c"  # Overlay1

[buffer]
action = "#f5e0dc"      # Rosewater
background = "#1e1e2e"  # Base
background_text_input = "#181825"  # Mantle
background_title_bar = "#11111b"   # Crust
border = "#313244"      # Surface0
border_selected = "#89b4fa"  # Blue
code = "#cba6f7"        # Mauve
highlight = "#fab387"   # Peach
nickname = "#89b4fa"    # Blue
selection = "#45475a"   # Surface1
timestamp = "#6c7086"   # Overlay0
topic = "#b4befe"       # Lavender
url = "#89b4fa"         # Blue
